In [1]:
from matrix import Matrix

In [2]:
m = Matrix(3,3)

In [3]:
m.show_matrix()

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
m.identity_matrix()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
m.diagonal_matrix()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
m.triangular_supp_matrix()

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [7]:
m.triangular_inf_matrix()

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [8]:
m.transpose_matrix()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
m.mean_matrix()

np.float64(1.0)

In [10]:
m.var_matrix()

np.float64(0.0)

In [11]:
m.std_matrix()

np.float64(0.0)

In [12]:
n = Matrix(3,3)

m.dot_matrix(n)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [14]:
m.det_matrix()

np.int64(0)