In [10]:
from matrix import Matrix

In [11]:
m = Matrix(3,3)

In [12]:
m.show_matrix()

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
m.identity_matrix()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
m.diagonal_matrix()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
m.triangular_supp_matrix()

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [16]:
m.triangular_inf_matrix()

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [17]:
m.transpose_matrix()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
m.mean_matrix()

np.float64(1.0)

In [19]:
m.var_matrix()

np.float64(0.0)

In [20]:
m.std_matrix()

np.float64(0.0)