In [ ]:
from td_numpy.Matrix import Matrix

In [2]:
m = Matrix(3)

In [3]:
m.show_matrix()

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
m.identity_matrix()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
m.triangular_supp_matrix()

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [7]:
m.triangular_inf_matrix()

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])